apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - model.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: chatbot
    includeSelectors: false
